baseURL = 'https://tno.github.io/awesome-sbom/'
languageCode = 'en-us'
title = 'Awesome SBOM'

[outputs]
    home = ["HTML", "JSON"]

[[menu.main]]
  name   = "Tools"
  url    = "/"
  weight = 1

[[menu.main]]
  name   = "SBOM Lifecycle"
  url    = "/sbom-lifecycle/"
  weight = 2

[params]
  description = "Awesome SBOM — a one-stop overview of SBOM tooling"
  logo = "images/logo.webp"
  tagline = "One stop shop for SBOM tooling information"

[caches]
  [caches.images]
    dir = ':cacheDir/images'
